In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import os

In [ ]:
df = pd.read_csv("/content/diabetes_binary_5050split_health_indicators_BRFSS2015.csv")

In [ ]:
df.head()

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0              0.0     1.0       0.0        1.0  26.0     0.0     0.0   
1              0.0     1.0       1.0        1.0  26.0     1.0     1.0   
2              0.0     0.0       0.0        1.0  26.0     0.0     0.0   
3              0.0     1.0       1.0        1.0  28.0     1.0     0.0   
4              0.0     0.0       0.0        1.0  29.0     1.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           1.0     0.0  ...            1.0   
1                   0.0           0.0     1.0  ...            1.0   
2                   0.0           1.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  \
0          0.0      3.0       5.0      30.0       0.0  1.0   4.0        6.0   
1          0.0      3.0       0.0       0.0       0.0  1.0  12.0        6.0   
2          0.0      1.0       0.0      10.0       0.0  1.0  13.0        6.0   
3          0.0      3.0       0.0       3.0       0.0  1.0  11.0        6.0   
4          0.0      2.0       0.0       0.0       0.0  0.0   8.0        5.0   

   Income  
0     8.0  
1     8.0  
2     8.0  
3     8.0  
4     8.0  

[5 rows x 22 columns]

In [ ]:
df.tail()

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
46763              1.0     1.0       1.0        1.0  31.0     0.0     0.0   
46764              1.0     1.0       0.0        1.0  30.0     0.0     1.0   
46765              1.0     1.0       0.0        1.0  25.0     1.0     0.0   
46766              1.0     0.0       0.0        1.0  60.0     1.0     1.0   
46767              1.0     1.0       1.0        1.0  27.0     0.0     0.0   

       HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
46763                   0.0           0.0     1.0  ...            1.0   
46764                   0.0           1.0     1.0  ...            1.0   
46765                   0.0           1.0     1.0  ...            1.0   
46766                   0.0           0.0     1.0  ...            1.0   
46767                   0.0           1.0     1.0  ...            1.0   

       NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  \
46763          0.0      4.0      30.0      20.0       1.0  0.0   8.0   
46764          0.0      3.0       0.0       0.0       0.0  0.0  10.0   
46765          0.0      4.0       0.0       3.0       1.0  1.0   8.0   
46766          0.0      3.0       0.0       0.0       1.0  0.0   8.0   
46767          0.0      2.0       0.0       0.0       0.0  0.0   NaN   

       Education  Income  
46763        4.0     8.0  
46764        6.0     2.0  
46765        5.0     2.0  
46766        5.0     4.0  
46767        NaN     NaN  

[5 rows x 22 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46768 entries, 0 to 46767
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Diabetes_binary       46768 non-null  float64
 1   HighBP                46768 non-null  float64
 2   HighChol              46768 non-null  float64
 3   CholCheck             46768 non-null  float64
 4   BMI                   46768 non-null  float64
 5   Smoker                46768 non-null  float64
 6   Stroke                46768 non-null  float64
 7   HeartDiseaseorAttack  46768 non-null  float64
 8   PhysActivity          46768 non-null  float64
 9   Fruits                46768 non-null  float64
 10  Veggies               46768 non-null  float64
 11  HvyAlcoholConsump     46768 non-null  float64
 12  AnyHealthcare         46768 non-null  float64
 13  NoDocbcCost           46768 non-null  float64
 14  GenHlth               46768 non-null  float64
 15  MentHlth           

In [ ]:
df.describe()

Diabetes_binary        HighBP      HighChol     CholCheck  \
count     46768.000000  46768.000000  46768.000000  46768.000000   
mean          0.244227      0.467178      0.452446      0.965917   
std           0.429632      0.498927      0.497739      0.181445   
min           0.000000      0.000000      0.000000      0.000000   
25%           0.000000      0.000000      0.000000      1.000000   
50%           0.000000      0.000000      0.000000      1.000000   
75%           0.000000      1.000000      1.000000      1.000000   
max           1.000000      1.000000      1.000000      1.000000   

                BMI        Smoker        Stroke  HeartDiseaseorAttack  \
count  46768.000000  46768.000000  46768.000000          46768.000000   
mean      28.790498      0.451591      0.046912              0.109776   
std        6.886169      0.497656      0.211454              0.312614   
min       12.000000      0.000000      0.000000              0.000000   
25%       24.000000      0.000000      0.000000              0.000000   
50%       27.000000      0.000000      0.000000              0.000000   
75%       32.000000      1.000000      0.000000              0.000000   
max       98.000000      1.000000      1.000000              1.000000   

       PhysActivity        Fruits  ...  AnyHealthcare   NoDocbcCost  \
count  46768.000000  46768.000000  ...   46768.000000  46768.000000   
mean       0.742645      0.625898  ...       0.951420      0.088180   
std        0.437182      0.483895  ...       0.214991      0.283559   
min        0.000000      0.000000  ...       0.000000      0.000000   
25%        0.000000      0.000000  ...       1.000000      0.000000   
50%        1.000000      1.000000  ...       1.000000      0.000000   
75%        1.000000      1.000000  ...       1.000000      0.000000   
max        1.000000      1.000000  ...       1.000000      1.000000   

            GenHlth      MentHlth      PhysHlth      DiffWalk           Sex  \
count  46768.000000  46768.000000  46768.000000  46768.000000  46768.000000   
mean       2.602185      3.363389      4.698640      0.191605      0.445091   
std        1.093132      7.660326      9.160767      0.393568      0.496981   
min        1.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000      0.000000      0.000000      0.000000      0.000000   
50%        3.000000      0.000000      0.000000      0.000000      0.000000   
75%        3.000000      2.000000      4.000000      0.000000      1.000000   
max        5.000000     30.000000     30.000000      1.000000      1.000000   

                Age     Education        Income  
count  46767.000000  46767.000000  46767.000000  
mean       8.181346      5.018175      5.967734  
std        3.004960      1.002313      2.104324  
min        1.000000      1.000000      1.000000  
25%        6.000000      4.000000      5.000000  
50%        9.000000      5.000000      7.000000  
75%       10.000000      6.000000      8.000000  
max       13.000000      6.000000      8.000000  

[8 rows x 22 columns]

In [ ]:
df.shape

(46768, 22)

In [ ]:
df = df.dropna()        #drop rows with null values

In [ ]:
df.head()

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0              0.0     1.0       0.0        1.0  26.0     0.0     0.0   
1              0.0     1.0       1.0        1.0  26.0     1.0     1.0   
2              0.0     0.0       0.0        1.0  26.0     0.0     0.0   
3              0.0     1.0       1.0        1.0  28.0     1.0     0.0   
4              0.0     0.0       0.0        1.0  29.0     1.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           1.0     0.0  ...            1.0   
1                   0.0           0.0     1.0  ...            1.0   
2                   0.0           1.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  \
0          0.0      3.0       5.0      30.0       0.0  1.0   4.0        6.0   
1          0.0      3.0       0.0       0.0       0.0  1.0  12.0        6.0   
2          0.0      1.0       0.0      10.0       0.0  1.0  13.0        6.0   
3          0.0      3.0       0.0       3.0       0.0  1.0  11.0        6.0   
4          0.0      2.0       0.0       0.0       0.0  0.0   8.0        5.0   

   Income  
0     8.0  
1     8.0  
2     8.0  
3     8.0  
4     8.0  

[5 rows x 22 columns]

In [ ]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,roc_curve,auc

In [ ]:
Xs = df.drop(columns = 'Diabetes_binary')       #independent variable array
ys = df['Diabetes_binary']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    Xs, ys, test_size=0.2, random_state=42)

In [ ]:
#standardize the features

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
#train the logistic regression model
model = LogisticRegression()
model.fit(X_train ,y_train)

LogisticRegression()

In [ ]:
#evaluate the model
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

Accuracy: 78.76%


In [ ]:
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[6502  582]
 [1405  865]]


In [ ]:
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n",classification_report(y_test, y_pred))

Confusion Matrix:
 [[6502  582]
 [1405  865]]

Classification Report:
               precision    recall  f1-score   support

         0.0       0.82      0.92      0.87      7084
         1.0       0.60      0.38      0.47      2270

    accuracy                           0.79      9354
   macro avg       0.71      0.65      0.67      9354
weighted avg       0.77      0.79      0.77      9354



In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor()

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
y_rpred = rf.predict(X_test)

In [ ]:
y_pred

array([0., 0., 1., ..., 0., 1., 0.])

In [ ]:
y_rpred

array([0., 0., 1., ..., 0., 0., 1.])

In [ ]:
y_test

43476    1.0
3068     0.0
1012     0.0
17707    0.0
36356    1.0
        ... 
11196    0.0
20217    0.0
40371    1.0
44092    1.0
39978    1.0
Name: Diabetes_binary, Length: 9354, dtype: float64

In [ ]:
name = 'Random Forest'
accuracy = accuracy_score(y_test, y_rpred)
precision = precision_score(y_test, y_rpred)
recall = recall_score(y_test, y_rpred)
f1 = f1_score(y_test, y_rpred)
roc_auc = roc_auc_score(y_test, y_rpred)

#print result
print(f'Classifier: {name}')
print(f'Accuracy: {accuracy:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Recall: {recall:.4f}')
print(f"F1 Score: {f1:.4f}")
print(f'ROC AUC Score: {roc_auc:.4f}')
print('\n')

name = 'LogisticRegression'
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred)

#print result
print(f'Classifier: {name}')
print(f'Accuracy: {accuracy:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Recall: {recall:.4f}')
print(f"F1 Score: {f1:.4f}")
print(f'ROC AUC Score: {roc_auc:.4f}')
print('\n')

Classifier: Random Forest
Accuracy: 0.7857
Precision: 0.5844
Recall: 0.4040
F1 Score: 0.4777
ROC AUC Score: 0.6560


Classifier: LogisticRegression
Accuracy: 0.7876
Precision: 0.5978
Recall: 0.3811
F1 Score: 0.4654
ROC AUC Score: 0.6495


